# Generated by Django 3.2.5 on 2021-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0002_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='downvotes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='upvotes',
            field=models.BigIntegerField(default=0),
        ),
    ]
