# Generated by Django 3.2.5 on 2021-08-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0003_auto_20210805_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='downvotes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='upvotes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
